runtime: python311
entrypoint: gunicorn -b :$PORT bot:app

env_variables:
  TELEGRAM_BOT_TOKEN: your_token_here
  SPREADSHEET_ID: your_spreadsheet_id
  CREDENTIALS_JSON_BASE64: your_base64_encoded_json_credentials
  ADMIN_CHAT_IDS: 123456789